api:
    resource: "@AppBundle/Resources/config/api_routing.yml"
    prefix:   /api

app:
    resource: "@AppBundle/Resources/config/app_routing.yml"
    prefix:   /app

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"