security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email  # fos_user.user_provider.username_email does not seem to work (OAuth-spec related ("username + password") ?)

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

        oauth_token:
            pattern: ^/oauth/v2/token
            security: false

        api:
            pattern: ^/api(?!/doc)
            fos_oauth: true
            stateless: true
            anonymous: false